name: Lighthouse

on:
  pull_request:
    branches: [main]

jobs:
  lhci:
    name: CI
    uses: The-Adult-In-The-Room/ci-workflows/.github/workflows/lighthouse.yml@v1.0.0
    secrets:
      lhci-github-app-token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
