name: Verify

on:
  pull_request:
    branches: [main]

jobs:
  verify:
    name: CI
    uses: The-Adult-In-The-Room/ci-workflows/.github/workflows/verify.yml@v2.0.0
    with:
      run-lighthouse: true
    secrets:
      lhci-github-app-token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
